// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALta9YT7KXk5m0MyEFPhbDpX89jIglWLU',
    appId: '1:253520301936:web:ccb5976ac3e3432b5f49b5',
    messagingSenderId: '253520301936',
    projectId: 'spotifyapp-ef957',
    authDomain: 'spotifyapp-ef957.firebaseapp.com',
    storageBucket: 'spotifyapp-ef957.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYiNzcIZxSOa_ve4YP-dYdh_FwCLUTKiA',
    appId: '1:253520301936:android:daae5eacd19171aa5f49b5',
    messagingSenderId: '253520301936',
    projectId: 'spotifyapp-ef957',
    storageBucket: 'spotifyapp-ef957.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBphYAGnmyLGp_Hdg_PCfjF1Pepc-clOoE',
    appId: '1:253520301936:ios:7566826c701f55995f49b5',
    messagingSenderId: '253520301936',
    projectId: 'spotifyapp-ef957',
    storageBucket: 'spotifyapp-ef957.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBphYAGnmyLGp_Hdg_PCfjF1Pepc-clOoE',
    appId: '1:253520301936:ios:7566826c701f55995f49b5',
    messagingSenderId: '253520301936',
    projectId: 'spotifyapp-ef957',
    storageBucket: 'spotifyapp-ef957.firebasestorage.app',
    iosBundleId: 'com.example.spotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALta9YT7KXk5m0MyEFPhbDpX89jIglWLU',
    appId: '1:253520301936:web:377daad84b0e24275f49b5',
    messagingSenderId: '253520301936',
    projectId: 'spotifyapp-ef957',
    authDomain: 'spotifyapp-ef957.firebaseapp.com',
    storageBucket: 'spotifyapp-ef957.firebasestorage.app',
  );
}
